
import { GoogleGenAI } from "@google/genai";

export class GeminiService {
  private ai: GoogleGenAI;

  constructor() {
    this.ai = new GoogleGenAI({ apiKey: process.env.API_KEY || '' });
  }

  async performTryOn(personImage: string, clothingImage: string): Promise<string> {
    // Extract base64 and mime type from data URLs
    const parseDataUrl = (dataUrl: string) => {
      const matches = dataUrl.match(/^data:([^;]+);base64,(.+)$/);
      if (!matches) throw new Error("Invalid image format");
      return { mimeType: matches[1], data: matches[2] };
    };

    const person = parseDataUrl(personImage);
    const clothing = parseDataUrl(clothingImage);

    try {
      const response = await this.ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
          parts: [
            {
              inlineData: {
                data: person.data,
                mimeType: person.mimeType,
              },
            },
            {
              inlineData: {
                data: clothing.data,
                mimeType: clothing.mimeType,
              },
            },
            {
              text: `TASK: Virtual Try-On. 
              Image 1: A person.
              Image 2: A clothing item.
              
              INSTRUCTION: Create a highly realistic, professional fashion photograph where the person from Image 1 is wearing the exact clothing item from Image 2.
              
              REQUIREMENTS:
              - Replace the person's current outfit with the item from Image 2.
              - Preserve the person's identity: facial features, body shape, pose, skin tone, and hair.
              - The clothing must fit naturally on the body with realistic folds, shadows, and fabric textures.
              - Maintain the original lighting and background of the person image for a seamless look.
              - Ensure high-resolution quality with no distortions.
              
              SAFETY:
              - The result must be professional and safe.
              - The person must remain fully clothed.
              - Strictly no nudity or suggestive content.
              
              OUTPUT: Return ONLY the generated image.`
            }
          ]
        }
      });

      // Find the image part in candidates
      if (response.candidates && response.candidates[0].content.parts) {
        for (const part of response.candidates[0].content.parts) {
          if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
          }
          if (part.text && (part.text.includes("safety") || part.text.includes("refuse"))) {
            throw new Error("The request was flagged by safety filters. Please ensure images are appropriate.");
          }
        }
      }
      
      throw new Error("No image was generated by the model. It might have been a safety refusal or technical error.");
    } catch (error: any) {
      console.error("Gemini API Error:", error);
      throw new Error(error.message || "Failed to generate try-on image.");
    }
  }
}

export const geminiService = new GeminiService();
